### ISSUE TITLE
Import Hdidx issue on Windows 10

### ISSUE THREAD

**Issue by ivan-marroquin** [hdidx/hdidx#10]
Hi,

I have a windows 10 with Python 3.6.5. I followed the instructions:
- download stdint.h and put the file in the specified path in windows
- run the command "pip install opencv-python"
- run the command "pip install cython"
- run the command "pip install hdidx"

when I launch Python and do "import hdidx", I get this error:

  File "C:\Temp\Python\Python36\lib\site-packages\hdidx\__init__.py", line 12, in <module>
    import indexer
ModuleNotFoundError: No module named 'indexer'

Any suggestions?

Many thanks,
Ivan

**Comment by ivan-marroquin** [comment]
Hi,

I got the same issue on an Ubuntu 18.04 with Python 3.6.5

Kind regards,
Ivan

**Comment by SmallStrawHat** [comment]
Since the code has not been updated for a long time, you may have some problems using the latest environment. For example xrange needs to be replaced with range and so on.

If you just want to use the ANN python library, you can check out this https://github.com/spotify/annoy

**Comment by ivan-marroquin** [comment]
Thanks a lot for the suggestion
