### ISSUE TITLE
Fix bottleneck version problem

### ISSUE THREAD

**Issue by willard-yuan** [hdidx/hdidx#6]
Hi @wanji @stevenhoi 

Since from bottleneck 1.2.0, functions partsort and argpartsort have been renamed to partition and argpartition to match NumPy [Release Notes](https://github.com/kwgoodman/bottleneck/blob/master/RELEASE.rst)
So in `util.py` line [L83](https://github.com/hdidx/hdidx/blob/master/hdidx/util.py#L83), if the bottleneck version is 1.2.0 or higher, it will cause an error, one should do fix the error by replacing 

```python
ids = bottleneck.argpartsort(dist, topk)[:topk]
```

to 

```python
ids = bottleneck.argpartition(dist, topk-1)[:topk]
```

**Comment by wanji** [comment]
Fixed. Thanks (:
